sudo: required

language: php

services:
  - docker
  
php:
  - 5.6
  
before_script:
  - phpenv config-rm xdebug.ini
 
before_install:
  - sudo apt-get update
  - echo "extension = mongo.so" >> ~/.phpenv/versions/5.6/etc/php.ini
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
  - docker build -t ticokaic/exileinfo .
  - docker run -d ticokaic/exileinfo 
  
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push ticokaic/exileinfo;
    fi
  
script: phpunit tests.php
