sudo: required

language: php

services:
  - docker
  
php:
  - 5.4
  - 5.5
  - 5.6
 
before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
  - docker build -t ticokaic/exileinfo .
  - docker run -d -e MONGODBURI="$MONGOURI" ticokaic/exileinfo 
  
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push ticokaic/exileinfo;
    fi
  
script: phpunit tests.php
